name: File Sync

on:
  push:
    paths:
      - 'fg-luacheck-action.yml'
      - 'sync-luacheck.yml'
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Syncing File
        uses: kbrashears5/github-action-file-sync@2.0.11
        with:
          REPOSITORIES: |
            FG-Unofficial-Developers-Guild/FG-4E-TEMPO-and-TEMPA@main
            FG-Unofficial-Developers-Guild/FG-Aura-Effect@main
            FG-Unofficial-Developers-Guild/FG-ClockAdjuster@main
            FG-Unofficial-Developers-Guild/FG-CoreRPG-Moon-Tracker@main
            FG-Unofficial-Developers-Guild/FG-CoreRPG-Party-Inventory-Identified@main
            FG-Unofficial-Developers-Guild/FG-CoreRPG-Party-Inventory-Weight@main
            FG-Unofficial-Developers-Guild/FG-PFRPG-Advanced-Item-Actions@main
            FG-Unofficial-Developers-Guild/FG-PFRPG-Customized-Item-Generator@main
            FG-Unofficial-Developers-Guild/FG-PFRPG-Enhanced-Items@main
            FG-Unofficial-Developers-Guild/FG-PFRPG-ExtendedACBonusTypes@main
            bmos/FG-Ammunition-Manager@main
            bmos/FG-CoreRPG-Coins-Weight@main
            bmos/FG-CoreRPG-Extraplanar-Containers@main
            bmos/FG-PFRPG-Drain-and-Permanent-Bonuses@main
            bmos/FG-PFRPG-Encumbrance-Penalties@main
            bmos/FG-PFRPG-Extra-Stat-to-Saves@main
            bmos/FG-PFRPG-Item-Durability@main
            bmos/FG-PFRPG-Live-Hitpoints@main
            bmos/FG-PFRPG-Malady-Tracker@main
            bmos/FG-PFRPG-Sanity-Tracker@main
            bmos/FG-PFRPG-Spell-Failure@main
            bmos/FG-PFRPG-Spell-Formatting@main
            bmos/FG-PFRPG-Upgrade-NPC-Actions@main
          FILES: |
            fg-luacheck-action.yml=.github/workflows/luacheck.yml
          TOKEN: ${{ secrets.ACTIONS }}
